name: Build Multi-Arch Docker Image (amd64/arm64)
on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          line-ending: lf
      - name: Fix file line endings & remove CR
        run: |
          sudo apt install -y dos2unix
          find . -type f -exec dos2unix {} \;
      - name: Set up stable QEMU v8.1.5
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.GHCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args:
            NPM_REGISTRY=https://registry.npmmirror.com
